apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-quote-app-backend
  labels:
    app: car-quote-app
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-quote-app
      component: backend
  template:
    metadata:
      labels:
        app: car-quote-app
        component: backend
    spec:
      initContainers:
      - name: init-data
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - |
          mkdir -p /app/data
          echo '[
            {"id": "Q1001", "customer": "John Smith", "email": "john@example.com", "phone": "555-123-4567", "date": "2025-04-28", "vehicle": "2023 Toyota Camry (Standard)", "coverage": "Premium", "premium": "$1,250.00", "status": "new", "zip": "90210"},
            {"id": "Q1002", "customer": "Maria Garcia", "email": "maria@example.com", "phone": "555-234-5678", "date": "2025-04-28", "vehicle": "2024 Honda Civic (Economy)", "coverage": "Standard", "premium": "$980.00", "status": "new", "zip": "33178"},
            {"id": "Q1003", "customer": "Robert Johnson", "email": "robert@example.com", "phone": "555-345-6789", "date": "2025-04-27", "vehicle": "2022 Ford F-150 (Standard)", "coverage": "Premium", "premium": "$1,550.00", "status": "contacted", "zip": "60007"},
            {"id": "Q1004", "customer": "Sarah Williams", "email": "sarah@example.com", "phone": "555-456-7890", "date": "2025-04-26", "vehicle": "2024 Chevrolet Equinox (Standard)", "coverage": "Basic", "premium": "$820.00", "status": "pending", "zip": "10001"},
            {"id": "Q1005", "customer": "Michael Brown", "email": "michael@example.com", "phone": "555-567-8901", "date": "2025-04-25", "vehicle": "2023 Tesla Model 3 (Luxury)", "coverage": "Premium", "premium": "$1,680.00", "status": "new", "zip": "98101"},
            {"id": "Q1006", "customer": "Jennifer Davis", "email": "jennifer@example.com", "phone": "555-678-9012", "date": "2025-04-25", "vehicle": "2022 Nissan Altima (Standard)", "coverage": "Standard", "premium": "$1,020.00", "status": "converted", "zip": "75001"},
            {"id": "Q1007", "customer": "David Miller", "email": "david@example.com", "phone": "555-789-0123", "date": "2025-04-24", "vehicle": "2025 Hyundai Tucson (Standard)", "coverage": "Basic", "premium": "$850.00", "status": "new", "zip": "20001"},
            {"id": "Q1008", "customer": "Lisa Wilson", "email": "lisa@example.com", "phone": "555-890-1234", "date": "2025-04-24", "vehicle": "2021 BMW 3 Series (Luxury)", "coverage": "Premium", "premium": "$1,790.00", "status": "pending", "zip": "02108"},
            {"id": "Q1009", "customer": "James Taylor", "email": "james@example.com", "phone": "555-901-2345", "date": "2025-04-23", "vehicle": "2024 Kia Sorento (Standard)", "coverage": "Standard", "premium": "$1,150.00", "status": "contacted", "zip": "80202"},
            {"id": "Q1010", "customer": "Patricia Anderson", "email": "patricia@example.com", "phone": "555-012-3456", "date": "2025-04-23", "vehicle": "2022 Toyota RAV4 (Standard)", "coverage": "Basic", "premium": "$920.00", "status": "new", "zip": "30303"},
            {"id": "Q1011", "customer": "Thomas Martinez", "email": "thomas@example.com", "phone": "555-123-4567", "date": "2025-04-22", "vehicle": "2023 Lexus ES (Luxury)", "coverage": "Premium", "premium": "$1,690.00", "status": "converted", "zip": "85001"},
            {"id": "Q1012", "customer": "Elizabeth Robinson", "email": "elizabeth@example.com", "phone": "555-234-5678", "date": "2025-04-22", "vehicle": "2024 Honda Accord (Standard)", "coverage": "Standard", "premium": "$1,110.00", "status": "new", "zip": "46204"},
            {"id": "Q1013", "customer": "Charles Clark", "email": "charles@example.com", "phone": "555-345-6789", "date": "2025-04-21", "vehicle": "2022 Ford Escape (Economy)", "coverage": "Basic", "premium": "$840.00", "status": "pending", "zip": "19019"},
            {"id": "Q1014", "customer": "Susan Rodriguez", "email": "susan@example.com", "phone": "555-456-7890", "date": "2025-04-21", "vehicle": "2025 Audi A4 (Luxury)", "coverage": "Premium", "premium": "$1,850.00", "status": "new", "zip": "92101"},
            {"id": "Q1015", "customer": "Joseph Lee", "email": "joseph@example.com", "phone": "555-567-8901", "date": "2025-04-20", "vehicle": "2023 Subaru Outback (Standard)", "coverage": "Standard", "premium": "$1,050.00", "status": "contacted", "zip": "97204"}
          ]' > /app/data/quotes.json
          chmod 666 /app/data/quotes.json
          echo "Copied quotes.json to PVC"
        volumeMounts:
        - name: backend-data
          mountPath: /app/data
      containers:
      - name: backend
        image: image-registry.openshift-image-registry.svc:5000/car-quote-demo/car-quote-app-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: backend-data
          mountPath: /app/data
      volumes:
      - name: backend-data
        persistentVolumeClaim:
          claimName: car-quote-app-backend-data
