apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-quote-app-backend
  labels:
    app: car-quote-app
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-quote-app
      component: backend
  template:
    metadata:
      labels:
        app: car-quote-app
        component: backend
    spec:
      containers:
      - name: backend
        image: image-registry.openshift-image-registry.svc:5000/car-quote-demo/car-quote-app-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: backend-data
          mountPath: /app
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: backend-data
        persistentVolumeClaim:
          claimName: car-quote-app-backend-data
