apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: car-quote-app-backend-data
  labels:
    app: car-quote-app
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
